
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: demo2
    name: demo2
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: demo2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: demo2
      spec:
        containers:
        - image: docker.io/kumarisbeck/micro-servicetwo:0.0.11-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: micro-servicetwo
          resources :
          # set resources to use autoscaling features
            limits: 
              cpu: 200m
            requests :
              cpu : 200m
          readinessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/liveness

          securityContext:
            capabilities:
              drop:
              - NET_RAW
        restartPolicy: Always
        tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
  

---


  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: demo2
    name: demo2
    namespace: default
  spec:
    allocateLoadBalancerNodePorts: true
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: demo2
    sessionAffinity: None
    type: LoadBalancer
  
